version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - my_network  
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - my_network

networks:
  my_network:
